=== agentile/GREC-MRS/GREC_XML/GRECResources/GREC_event.dtd
<!-- ============================================================ -->
<!-- DTD for GREC with concept &    event annotation              -->
<!-- Modified by Paul Thompson <paul.thompson@manchester.ac.uk>   -->
<!-- from the original GENIA DTD written by Jin-Dong KIM          -->
<!-- <jdkim@tsujii.is.s.u-tokyo.ac.jp>  				      -->
<!-- Date of last modification: 28 August 2009                    -->
<!-- ============================================================ -->

<!-- ============================================================ -->
<!-- Labels for concept&event annotation                             -->
<!-- ============================================================ -->
<!ENTITY % term.class "(
 Polypeptide | Peptide | Protein_Complex | Protein | Amino_Acids |
 Conformation | Sub_Unit | Motif | Domain | Transcription_Factor |
 Enzyme | Regulator | Sigma_Factor | Repressor | Rho-Factor |
 Activator | RNA_Polymerase | DNA_Polymerase | Restriction_Enzyme |
 Chromosome | Plasmid | Viral_Vector | RNA | DNA | Gene | Operon |
 Locus | Mutant_Gene | ORF | Allele | Transcription_Binding_Site |
 Termination_Site | Phenotype | Ribosome | mRNA | Promoter | Operator |
 Enhancer | Prokaryotes | Virus | Eukaryotes | Bacteria | Non-Bacteria |
 Wild_Type_Bacteria | Mutant_Bacteria | Organism | Tissue | Cells |Organelles |
 Wild_Type_Organism | Mutant_Organism | Gene_Expression |
 Mutation | Transcription | Replication | Recombination | Methylation | Regulation |
 Gene_Activation | Gene_Repression | Insertion | Deletion | Null_Mutation | Point_Mutation |
 Reagents | Experimental_Technique | Experimental_Equipment | Inorganic_Compounds | 
 Organic_Compounds | Other_Compounds | Laboratory_Technique | Computational_Analysis | SPAN 
)">

<!-- ============================================================ -->
<!-- HIERARCHICAL ELEMENTS                                        -->
<!-- ============================================================ -->
<!ELEMENT Annotation (PubmedArticleSet)>
<!ATTLIST Annotation
		annotates CDATA #REQUIRED
		creator   CDATA #IMPLIED
		created   CDATA #IMPLIED
>

<!ELEMENT PubmedArticleSet (PubmedArticle)>
<!ELEMENT PubmedArticle (MedlineCitation)>
<!ELEMENT MedlineCitation (PMID, Article)>
<!ELEMENT Article (ArticleTitle, Abstract)>
<!ELEMENT Abstract (AbstractText)>

<!-- ============================================================ -->
<!-- BLOCK ELEMENTS                                               -->
<!-- ============================================================ -->
<!ELEMENT ArticleTitle (sentence | event)+>
<!ELEMENT AbstractText (sentence | event)+>
<!ELEMENT PMID (#PCDATA)>

<!-- ============================================================ -->
<!-- LINGUISTIC ELEMENTS                                          -->
<!-- ============================================================ -->
<!ELEMENT sentence	(#PCDATA | term )*>
<!ATTLIST sentence	id ID	#REQUIRED>


<!ELEMENT term		(#PCDATA | term )*>
<!ATTLIST term
		sem %term.class;	#IMPLIED
		lex CDATA		#IMPLIED
		id  ID		#REQUIRED
>

<!-- ============================================================ -->
<!-- ELEMENTS FOR EVENT ANNOTATION                                -->
<!-- ============================================================ -->
<!ELEMENT event (type, (Agent | Theme | Manner | Instrument | Location | Source | Destination | 
Temporal | Condition | Rate | Descriptive-Agent | Descriptive-Theme | Purpose )+,
            clue)>
<!ATTLIST event
		id		ID				#REQUIRED
>

<!ELEMENT type EMPTY>
<!ATTLIST type class		CDATA	"UNCLASSIFIED">

<!ELEMENT Agent EMPTY>
<!ATTLIST Agent
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT Theme EMPTY>
<!ATTLIST Theme
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT Manner EMPTY>
<!ATTLIST Manner
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED

>

<!ELEMENT Instrument EMPTY>
<!ATTLIST Instrument
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED

>

<!ELEMENT Location EMPTY>
<!ATTLIST Location
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED

>

<!ELEMENT Source EMPTY>
<!ATTLIST Source
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED

>

<!ELEMENT Destination EMPTY>
<!ATTLIST Destination
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED

>

<!ELEMENT Temporal EMPTY>
<!ATTLIST Temporal
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED

>

<!ELEMENT Condition EMPTY>
<!ATTLIST Condition
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED

>

<!ELEMENT Rate EMPTY>
<!ATTLIST Rate
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED

>
<!ELEMENT Descriptive-Agent EMPTY>
<!ATTLIST Descriptive-Agent
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT Descriptive-Theme EMPTY>
<!ATTLIST Descriptive-Theme
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED

>
<!ELEMENT Purpose EMPTY>
<!ATTLIST Purpose
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>
<!ELEMENT Underspecified EMPTY>
<!ATTLIST Underspecified
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>



<!ELEMENT clue  (#PCDATA | clueType)*>

<!ELEMENT clueType		(#PCDATA)>

=== agentile/GREC-MRS/GREC_XML/Ecoli/11591675.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Annotation PUBLIC "-//GREC//DTD GREC EVENT ANNOTATION//EN" "../GRECResources/GREC_event.dtd">
<Annotation created="11/5/2009" creator="a4" annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;retmode=xml&amp;rettype=medline&amp;id=11591675">
<PubmedArticleSet>
<PubmedArticle>
<MedlineCitation>
<PMID>11591675</PMID>
<Article>
<ArticleTitle>
<sentence id="S1">Contributions of UP elements and the transcription factor FIS to expression from <term sem="Promoter" id="T1" lex="the_seven_rrn_P1_promoters">the seven rrn P1 promoters</term> <term sem="SPAN" id="T2" lex="in_Escherichia_coli">in <term sem="Bacteria" id="T3" lex="Escherichia_coli">Escherichia coli</term></term>.</sentence>
<event id="E1">
<type class="Gene_Expression" />
<Location idref="T2" />
<Source idref="T1" />
<clue>Contributions of UP elements and the transcription factor FIS to <clueType>expression</clueType> from the seven rrn P1 promoters in Escherichia coli.</clue>
</event>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S3"><term sem="SPAN" id="T4" lex="The_high_activity">The high activity</term> of the rrnB P1 promoter in Escherichia coli results from <term sem="DNA" id="T5" lex="a_cis-acting_DNA_sequence">a cis-acting DNA sequence</term>, <term sem="DNA" id="T6" lex="the_UP_element">the UP element</term>, and a trans-acting transcription factor, <term sem="Transcription_Factor" id="T7" lex="FIS">FIS</term>.</sentence>
<event id="E2">
<type class="GRE" />
<Agent idref="T5" idref1="T6" idref2="T7" />
<Theme idref="T4" />
<clue>The high activity of the rrnB P1 promoter in Escherichia coli <clueType>results</clueType> from a cis-acting DNA sequence, the UP element, and a trans-acting transcription factor, FIS.</clue>
</event>
<sentence id="S4">In this study, we examine the effects of <term sem="Transcription_Factor" id="T8" lex="FIS">FIS</term> and <term sem="DNA" id="T9" lex="the_UP_element">the UP element</term> <term sem="SPAN" id="T10" lex="at_the_other_six_rrn_P1_promoters">at <term sem="Promoter" id="T11" lex="the_other_six_rrn_P1_promoters">the other six rrn P1 promoters</term></term>.</sentence>
<event id="E3">
<type class="GRE" />
<Agent idref="T8" idref1="T9" />
<Location idref="T10" />
<clue>In this study, we examine the <clueType>effects</clueType> of FIS and the UP element at the other six rrn P1 promoters.</clue>
</event>
<sentence id="S5">We find that UP elements are present at all of the rrn P1 promoters, but they make different relative contributions to promoter activity.</sentence>
<sentence id="S6">Similarly, <term sem="Transcription_Factor" id="T12" lex="FIS">FIS</term> binds <term sem="SPAN" id="T13" lex="upstream_of">upstream of</term>, and activates, <term sem="Promoter" id="T14" lex="all_seven_rrn_P1_promoters">all seven rrn P1 promoters</term> but to different extents.</sentence>
<event id="E4">
<type class="GRE" />
<Agent idref="T12" />
<Destination idref="T13" idref1="T14" />
<clue>Similarly, FIS <clueType>binds</clueType> upstream of, and activates, all seven rrn P1 promoters but to different extents.</clue>
</event>
<event id="E5">
<type class="Gene_Activation" />
<Agent idref="T12" />
<Theme idref="T14" />
<clue>Similarly, FIS binds upstream of, and <clueType>activates</clueType>, all seven rrn P1 promoters but to different extents.</clue>
</event>
<sentence id="S7">The total number of FIS binding sites, as well as their positions relative to the transcription start site, differ at each rrn P1 promoter.</sentence>
<sentence id="S8">Surprisingly, the FIS sites upstream of site I play a much larger role in transcription from <term sem="Promoter" id="T15" lex="most_rrn_P1_promoters">most rrn P1 promoters</term> compared to rrnB P1.</sentence>
<event id="E6">
<type class="Transcription" />
<Source idref="T15" />
<clue>Surprisingly, the FIS sites upstream of site I play a much larger role in <clueType>transcription</clueType> from most rrn P1 promoters compared to rrnB P1.</clue>
</event>
<sentence id="S9">Our studies indicate that the overall activities of the seven rrn P1 promoters are similar, and the same contributors are responsible for these high activities, but these inputs make different relative contributions and may act through slightly different mechanisms at each promoter.</sentence>
<sentence id="S10">These studies have implications for the control of gene expression of <term sem="Gene" id="T16" lex="unlinked_multigene_families">unlinked multigene families</term>.</sentence>
<event id="E7">
<type class="GRE" />
<Theme idref="E8" />
<clue>These studies have implications for the <clueType>control</clueType> of gene expression of unlinked multigene families.</clue>
</event>
<event id="E8">
<type class="Gene_Expression" />
<Theme idref="T16" />
<clue>These studies have implications for the control of gene <clueType>expression</clueType> of unlinked multigene families.</clue>
</event>
</AbstractText>
</Abstract>
</Article>
</MedlineCitation>
</PubmedArticle>
</PubmedArticleSet>
</Annotation>

=== agentile/GREC-MRS/GREC_XML/Ecoli/7934873.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Annotation PUBLIC "-//GREC//DTD GREC EVENT ANNOTATION//EN" "../GRECResources/GREC_event.dtd">
<Annotation created="11/5/2009" creator="a6" annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;retmode=xml&amp;rettype=medline&amp;id=7934873">
<PubmedArticleSet>
<PubmedArticle>
<MedlineCitation>
<PMID>7934873</PMID>
<Article>
<ArticleTitle>
<sentence id="S1">DNA loop formation between <term sem="Repressor" id="T1" lex="Nag_repressor_molecules">Nag repressor molecules</term> bound to <term sem="Operator" id="T2" lex="its_two_operator_sites">its two operator sites</term> is necessary for repression of <term sem="Operon" id="T3" lex="the_nag_regulon">the nag regulon</term> of Escherichia coli <term sem="SPAN" id="T4" lex="in_vivo">in vivo</term>.</sentence>
<event id="E1">
<type class="GRE" />
<Agent idref="T1" />
<Destination idref="T2" />
<clue>DNA loop formation between Nag repressor molecules <clueType>bound</clueType> to its two operator sites is necessary for repression of the nag regulon of Escherichia coli in vivo.</clue>
</event>
<event id="E2">
<type class="Gene_Repression" />
<Theme idref="T3" />
<Manner idref="T4" />
<clue>DNA loop formation between Nag repressor molecules bound to its two operator sites is necessary for <clueType>repression</clueType> of the nag regulon of Escherichia coli in vivo.</clue>
</event>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S3"><term sem="Transcription_Binding_Site" id="T5" lex="Binding_sites">Binding sites</term> for the Nag repressor overlap <term sem="Promoter" id="T6" lex="the_transcription_start_sites">the transcription start sites</term> of the divergent nagE and nagB genes, such that the centres of the sites are separated by nine turns of the B-DNA helix.</sentence>
<event id="E3">
<type class="GRE" />
<Theme idref="T5" />
<Descriptive-Theme idref="T6" />
<clue>Binding sites for the Nag repressor <clueType>overlap</clueType> the transcription start sites of the divergent nagE and nagB genes, such that the centres of the sites are separated by nine turns of the B-DNA helix.</clue>
</event>
<sentence id="S4"><term sem="Mutation" id="T7" lex="Mutations">Mutations</term> which prevent <term sem="Repressor" id="T8" lex="repressor">repressor</term> binding to <term sem="Transcription_Binding_Site" id="T9" lex="either_site">either site</term> or alter the phasing of the binding sites result in simultaneous derepression of <term sem="Gene" id="T10" lex="both_genes">both genes</term>.</sentence>
<event id="E4">
<type class="GRE" />
<Agent idref="T7" />
<Theme idref="E5" />
<clue>Mutations which <clueType>prevent</clueType> repressor binding to either site or alter the phasing of the binding sites result in simultaneous derepression of both genes.</clue>
</event>
<event id="E5">
<type class="GRE" />
<Agent idref="T8" />
<Destination idref="T9" />
<clue>Mutations which prevent repressor <clueType>binding</clueType> to either site or alter the phasing of the binding sites result in simultaneous derepression of both genes.</clue>
</event>
<event id="E6">
<type class="GRE" />
<Agent idref="T7" />
<Descriptive-Agent idref="E7" />
<clue>Mutations which prevent repressor binding to either site or alter the phasing of the binding sites <clueType>result</clueType> in simultaneous derepression of both genes.</clue>
</event>
<event id="E7">
<type class="Gene_Activation" />
<Theme idref="T10" />
<clue>Mutations which prevent repressor binding to either site or alter the phasing of the binding sites result in simultaneous <clueType>derepression</clueType> of both genes.</clue>
</event>
<sentence id="S5"><term sem="Mutation" id="T11" lex="An_additional_mutation">An additional mutation</term> which restores the phasing of the two sites permits <term sem="Gene_Repression" id="T12" lex="repression">repression</term>.</sentence>
<event id="E8">
<type class="GRE" />
<Agent idref="T11" />
<Theme idref="T12" />
<clue>An additional mutation which restores the phasing of the two sites <clueType>permits</clueType> repression.</clue>
</event>
<sentence id="S6">These observations show that repression is the result of <term sem="SPAN" id="T13" lex="co-operative">co-operative</term> binding of <term sem="SPAN" id="T14" lex="the_repressor">the repressor</term> to <term sem="Transcription_Binding_Site" id="T15" lex="its_two_sites">its two sites</term>, resulting in the formation of a loop of DNA.</sentence>
<event id="E9">
<type class="GRE" />
<Agent idref="T14" />
<Manner idref="T13" />
<Destination idref="T15" />
<clue>These observations show that repression is the result of co-operative <clueType>binding</clueType> of the repressor to its two sites, resulting in the formation of a loop of DNA.</clue>
</event>
</AbstractText>
</Abstract>
</Article>
</MedlineCitation>
</PubmedArticle>
</PubmedArticleSet>
</Annotation>

=== agentile/GREC-MRS/GREC_XML/Human/1630447.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Annotation PUBLIC "-//GREC//DTD GREC EVENT ANNOTATION//EN" "../GRECResources/GREC_event.dtd">
<Annotation created="11/5/2009" creator="a6" annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;retmode=xml&amp;rettype=medline&amp;id=1630447">
<PubmedArticleSet>
<PubmedArticle>
<MedlineCitation>
<PMID>1630447</PMID>
<Article>
<ArticleTitle>
<sentence id="S1">Subunit of an alpha-interferon-responsive transcription factor is related to interferon regulatory factor and Myb families of DNA-binding proteins.</sentence>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S3"><term sem="SPAN" id="T1" lex="Alpha_interferon">Alpha interferon</term> stimulates <term sem="Transcription" id="T2" lex="transcription">transcription</term> by converting <term sem="Transcription_Factor" id="T3" lex="the_positive_transcriptional_regulator_ISGF3">the positive transcriptional regulator ISGF3</term> from <term sem="SPAN" id="T4" lex="a_latent">a latent</term> to <term sem="SPAN" id="T5" lex="an_active_form">an active form</term>.</sentence>
<event id="E1">
<type class="Gene_Activation" />
<Agent idref="T1" />
<Theme idref="T2" />
<Instrument idref="E2" />
<clue>Alpha interferon <clueType>stimulates</clueType> transcription by converting the positive transcriptional regulator ISGF3 from a latent to an active form.</clue>
</event>
<event id="E2">
<type class="GRE" />
<Agent idref="T1" />
<Theme idref="T3" />
<Source idref="T4" />
<Destination idref="T5" />
<clue>Alpha interferon stimulates transcription by <clueType>converting</clueType> the positive transcriptional regulator ISGF3 from a latent to an active form.</clue>
</event>
<sentence id="S4"><term sem="SPAN" id="T6" lex="This_receptor-mediated_event">This receptor-mediated event</term> occurs <term sem="SPAN" id="T7" lex="in_the_cytoplasm">in <term sem="Organelles" id="T8" lex="the_cytoplasm">the cytoplasm</term></term>, with subsequent translocation of the activated factor to the nucleus.</sentence>
<event id="E3">
<type class="GRE" />
<Theme idref="T6" />
<Location idref="T7" />
<clue>This receptor-mediated event <clueType>occurs</clueType> in the cytoplasm, with subsequent translocation of the activated factor to the nucleus.</clue>
</event>
<sentence id="S5">ISGF3 has two components, termed ISGF3 alpha and ISGF3 gamma.</sentence>
<sentence id="S6"><term sem="Transcription_Factor" id="T9" lex="ISGF3_gamma">ISGF3 gamma</term> serves as <term sem="Sub_Unit" id="T10" lex="the_DNA_recognition_subunit">the DNA recognition subunit</term>, while <term sem="Transcription_Factor" id="T11" lex="ISGF3_alpha">ISGF3 alpha</term>, which appears to consist of three polypeptides, is a target for alpha interferon signaling and serves as <term sem="Sub_Unit" id="T12" lex="a_regulatory_component">a regulatory component</term> whose activation is required to form <term sem="Transcription_Factor" id="T13" lex="ISGF3">ISGF3</term>.</sentence>
<event id="E4">
<type class="GRE" />
<Agent idref="T9" />
<Descriptive-Agent idref="T10" />
<clue>ISGF3 gamma <clueType>serves</clueType> as the DNA recognition subunit, while ISGF3 alpha, which appears to consist of three polypeptides, is a target for alpha interferon signaling and serves as a regulatory component whose activation is required to form ISGF3.</clue>
</event>
<event id="E5">
<type class="GRE" />
<Agent idref="T11" />
<Descriptive-Agent idref="T12" />
<clue>ISGF3 gamma serves as the DNA recognition subunit, while ISGF3 alpha, which appears to consist of three polypeptides, is a target for alpha interferon signaling and <clueType>serves</clueType> as a regulatory component whose activation is required to form ISGF3.</clue>
</event>
<event id="E6">
<type class="GRE" />
<Theme idref="T11" />
<clue>ISGF3 gamma serves as the DNA recognition subunit, while ISGF3 alpha, which appears to consist of three polypeptides, is a target for alpha interferon signaling and serves as a regulatory component whose <clueType>activation</clueType> is required to form ISGF3.</clue>
</event>
<event id="E7">
<type class="GRE" />
<Theme idref="E6" />
<Purpose idref="E8" />
<clue>ISGF3 gamma serves as the DNA recognition subunit, while ISGF3 alpha, which appears to consist of three polypeptides, is a target for alpha interferon signaling and serves as a regulatory component whose activation is <clueType>required</clueType> to form ISGF3.</clue>
</event>
<event id="E8">
<type class="GRE" />
<Theme idref="T13" />
<clue>ISGF3 gamma serves as the DNA recognition subunit, while ISGF3 alpha, which appears to consist of three polypeptides, is a target for alpha interferon signaling and serves as a regulatory component whose activation is required to <clueType>form</clueType> ISGF3.</clue>
</event>
<sentence id="S7">ISGF3 gamma DNA-binding activity was identified as a 48-kDa polypeptide, and partial amino acid sequence has allowed isolation of cDNA clones.</sentence>
<sentence id="S8"><term sem="Transcription_Factor" id="T14" lex="ISGF3_gamma">ISGF3 gamma</term> translated in vitro from recombinant clones bound <term sem="DNA" id="T15" lex="DNA">DNA</term> with a specificity indistinguishable from that of ISGF3 gamma purified from HeLa cells.</sentence>
<event id="E9">
<type class="GRE" />
<Agent idref="T14" />
<Destination idref="T15" />
<clue>ISGF3 gamma translated in vitro from recombinant clones <clueType>bound</clueType> DNA with a specificity indistinguishable from that of ISGF3 gamma purified from HeLa cells.</clue>
</event>
<sentence id="S9">Sequencing of ISGF3 gamma cDNA clones revealed significant similarity to the interferon regulatory factor (IRF) family of DNA binding proteins in the amino-terminal 117 residues of ISGF3 gamma.</sentence>
<sentence id="S10"><term sem="Transcription_Factor" id="T16" lex="The_other_IRF_family_proteins">The other IRF family proteins</term> bind <term sem="DNA" id="T17" lex="DNA">DNA</term> with a specificity related to but distinct from that of ISGF3 gamma.</sentence>
<event id="E10">
<type class="GRE" />
<Agent idref="T16" />
<Destination idref="T17" />
<clue>The other IRF family proteins <clueType>bind</clueType> DNA with a specificity related to but distinct from that of ISGF3 gamma.</clue>
</event>
<sentence id="S11">We note sequence similarities between the related regions of IRF family proteins and the imperfect tryptophan repeats which constitute the DNA-binding domain of the c-myb oncoprotein.</sentence>
<sentence id="S12">These sequence similarities suggest that <term sem="Transcription_Factor" id="T18" lex="ISGF3_gamma">ISGF3 gamma</term> and <term sem="Transcription_Factor" id="T19" lex="IRF_proteins">IRF proteins</term> and <term sem="Transcription_Factor" id="T20" lex="the_c-myb_oncoprotein">the c-myb oncoprotein</term> use <term sem="Motif" id="T21" lex="a_common_structural_motif">a common structural motif</term> for <term sem="SPAN" id="T22" lex="DNA_recognition">DNA recognition</term>.</sentence>
<event id="E11">
<type class="GRE" />
<Agent idref="T18" idref1="T19" idref2="T20" />
<Purpose idref="T22" />
<Instrument idref="T21" />
<clue>These sequence similarities suggest that ISGF3 gamma and IRF proteins and the c-myb oncoprotein <clueType>use</clueType> a common structural motif for DNA recognition.</clue>
</event>
<sentence id="S13"><term sem="Protein" id="T23" lex="Recombinant_ISGF3_gamma">Recombinant ISGF3 gamma</term>, like the natural protein, interacted with <term sem="Protein" id="T24" lex="HeLa_cell_ISGF3_alpha">HeLa cell ISGF3 alpha</term> to form <term sem="Protein_Complex" id="T25" lex="the_mature_ISGF3_DNA-binding_complex">the mature ISGF3 DNA-binding complex</term>.</sentence>
<event id="E12">
<type class="GRE" />
<Theme idref="T23" />
<Theme idref="T24" />
<Purpose idref="E13" />
<clue>Recombinant ISGF3 gamma, like the natural protein, <clueType>interacted</clueType> with HeLa cell ISGF3 alpha to form the mature ISGF3 DNA-binding complex.</clue>
</event>
<event id="E13">
<type class="GRE" />
<Theme idref="T25" />
<clue>Recombinant ISGF3 gamma, like the natural protein, interacted with HeLa cell ISGF3 alpha to <clueType>form</clueType> the mature ISGF3 DNA-binding complex.</clue>
</event>
<sentence id="S14">We suggest that <term sem="Transcription_Factor" id="T26" lex="other_IRF_family_members">other IRF family members</term> may participate in <term sem="SPAN" id="T27" lex="signaling_pathways">signaling pathways</term> by interacting with <term sem="Sub_Unit" id="T28" lex="as_yet_unidentified_regulatory_subunits">as yet unidentified regulatory subunits</term> analogous to ISGF3 alpha.</sentence>
<event id="E14">
<type class="GRE" />
<Agent idref="T26" />
<Descriptive-Agent idref="T27" />
<Manner idref="E15" />
<clue>We suggest that other IRF family members may <clueType>participate</clueType> in signaling pathways by interacting with as yet unidentified regulatory subunits analogous to ISGF3 alpha.</clue>
</event>
<event id="E15">
<type class="GRE" />
<Theme idref="T26" />
<Theme idref="T28" />
<clue>We suggest that other IRF family members may participate in signaling pathways by <clueType>interacting</clueType> with as yet unidentified regulatory subunits analogous to ISGF3 alpha.</clue>
</event>
</AbstractText>
</Abstract>
</Article>
</MedlineCitation>
</PubmedArticle>
</PubmedArticleSet>
</Annotation>
