=== agentile/GREC-MRS/GREC_XML/GRECResources/GREC_event.dtd
<!-- ============================================================ -->
<!-- DTD for GREC with concept &    event annotation              -->
<!-- Modified by Paul Thompson <paul.thompson@manchester.ac.uk>   -->
<!-- from the original GENIA DTD written by Jin-Dong KIM          -->
<!-- <jdkim@tsujii.is.s.u-tokyo.ac.jp>  				      -->
<!-- Date of last modification: 28 August 2009                    -->
<!-- ============================================================ -->

<!-- ============================================================ -->
<!-- Labels for concept&event annotation                             -->
<!-- ============================================================ -->
<!ENTITY % term.class "(
 Polypeptide | Peptide | Protein_Complex | Protein | Amino_Acids |
 Conformation | Sub_Unit | Motif | Domain | Transcription_Factor |
 Enzyme | Regulator | Sigma_Factor | Repressor | Rho-Factor |
 Activator | RNA_Polymerase | DNA_Polymerase | Restriction_Enzyme |
 Chromosome | Plasmid | Viral_Vector | RNA | DNA | Gene | Operon |
 Locus | Mutant_Gene | ORF | Allele | Transcription_Binding_Site |
 Termination_Site | Phenotype | Ribosome | mRNA | Promoter | Operator |
 Enhancer | Prokaryotes | Virus | Eukaryotes | Bacteria | Non-Bacteria |
 Wild_Type_Bacteria | Mutant_Bacteria | Organism | Tissue | Cells |Organelles |
 Wild_Type_Organism | Mutant_Organism | Gene_Expression |
 Mutation | Transcription | Replication | Recombination | Methylation | Regulation |
 Gene_Activation | Gene_Repression | Insertion | Deletion | Null_Mutation | Point_Mutation |
 Reagents | Experimental_Technique | Experimental_Equipment | Inorganic_Compounds | 
 Organic_Compounds | Other_Compounds | Laboratory_Technique | Computational_Analysis | SPAN 
)">

<!-- ============================================================ -->
<!-- HIERARCHICAL ELEMENTS                                        -->
<!-- ============================================================ -->
<!ELEMENT Annotation (PubmedArticleSet)>
<!ATTLIST Annotation
		annotates CDATA #REQUIRED
		creator   CDATA #IMPLIED
		created   CDATA #IMPLIED
>

<!ELEMENT PubmedArticleSet (PubmedArticle)>
<!ELEMENT PubmedArticle (MedlineCitation)>
<!ELEMENT MedlineCitation (PMID, Article)>
<!ELEMENT Article (ArticleTitle, Abstract)>
<!ELEMENT Abstract (AbstractText)>

<!-- ============================================================ -->
<!-- BLOCK ELEMENTS                                               -->
<!-- ============================================================ -->
<!ELEMENT ArticleTitle (sentence | event)+>
<!ELEMENT AbstractText (sentence | event)+>
<!ELEMENT PMID (#PCDATA)>

<!-- ============================================================ -->
<!-- LINGUISTIC ELEMENTS                                          -->
<!-- ============================================================ -->
<!ELEMENT sentence	(#PCDATA | term )*>
<!ATTLIST sentence	id ID	#REQUIRED>


<!ELEMENT term		(#PCDATA | term )*>
<!ATTLIST term
		sem %term.class;	#IMPLIED
		lex CDATA		#IMPLIED
		id  ID		#REQUIRED
>

<!-- ============================================================ -->
<!-- ELEMENTS FOR EVENT ANNOTATION                                -->
<!-- ============================================================ -->
<!ELEMENT event (type, (Agent | Theme | Manner | Instrument | Location | Source | Destination | 
Temporal | Condition | Rate | Descriptive-Agent | Descriptive-Theme | Purpose )+,
            clue)>
<!ATTLIST event
		id		ID				#REQUIRED
>

<!ELEMENT type EMPTY>
<!ATTLIST type class		CDATA	"UNCLASSIFIED">

<!ELEMENT Agent EMPTY>
<!ATTLIST Agent
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT Theme EMPTY>
<!ATTLIST Theme
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT Manner EMPTY>
<!ATTLIST Manner
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED

>

<!ELEMENT Instrument EMPTY>
<!ATTLIST Instrument
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED

>

<!ELEMENT Location EMPTY>
<!ATTLIST Location
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED

>

<!ELEMENT Source EMPTY>
<!ATTLIST Source
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED

>

<!ELEMENT Destination EMPTY>
<!ATTLIST Destination
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED

>

<!ELEMENT Temporal EMPTY>
<!ATTLIST Temporal
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED

>

<!ELEMENT Condition EMPTY>
<!ATTLIST Condition
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED

>

<!ELEMENT Rate EMPTY>
<!ATTLIST Rate
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED

>
<!ELEMENT Descriptive-Agent EMPTY>
<!ATTLIST Descriptive-Agent
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT Descriptive-Theme EMPTY>
<!ATTLIST Descriptive-Theme
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED

>
<!ELEMENT Purpose EMPTY>
<!ATTLIST Purpose
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>
<!ELEMENT Underspecified EMPTY>
<!ATTLIST Underspecified
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>



<!ELEMENT clue  (#PCDATA | clueType)*>

<!ELEMENT clueType		(#PCDATA)>

=== agentile/GREC-MRS/GREC_XML/Human/9135990.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Annotation PUBLIC "-//GREC//DTD GREC EVENT ANNOTATION//EN" "../GRECResources/GREC_event.dtd">
<Annotation created="11/5/2009" creator="a2" annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;retmode=xml&amp;rettype=medline&amp;id=9135990">
<PubmedArticleSet>
<PubmedArticle>
<MedlineCitation>
<PMID>9135990</PMID>
<Article>
<ArticleTitle>
<sentence id="S1"><term sem="Repressor" id="T1" lex="BCL6">BCL6</term> can repress transcription from <term sem="Promoter" id="T2" lex="the_human_immunodeficiency_virus_type_I_promoter/enhancer_region">the human immunodeficiency virus type I promoter/enhancer region</term>.</sentence>
<event id="E1">
<type class="GRE" />
<Agent idref="T1" />
<Theme idref="E2" />
<clue>BCL6 can <clueType>repress</clueType> transcription from the human immunodeficiency virus type I promoter/enhancer region.</clue>
</event>
<event id="E2">
<type class="Transcription" />
<Source idref="T2" />
<clue>BCL6 can repress <clueType>transcription</clueType> from the human immunodeficiency virus type I promoter/enhancer region.</clue>
</event>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S3"><term sem="Gene" id="T3" lex="The_gene_BCL6">The gene BCL6</term> encodes <term sem="Repressor" id="T4" lex="a_zinc_finger_protein">a zinc finger protein</term> with similarities to transcription factors.</sentence>
<event id="E3">
<type class="GRE" />
<Agent idref="T3" />
<Theme idref="T4" />
<clue>The gene BCL6 <clueType>encodes</clueType> a zinc finger protein with similarities to transcription factors.</clue>
</event>
<sentence id="S4">We previously reported that a number of viral genomes, including human immunodeficiency virus type I (HIV-1), contain sequences which are similar to the BCL6 DNA-binding consensus in their promoter regions.</sentence>
<sentence id="S5">Electrophoretic mobility shift assays showed that <term sem="Repressor" id="T5" lex="the_full-length_BCL6_protein">the full-length BCL6 protein</term> extracted from transfected COS cells and <term sem="Protein" id="T6" lex="a_bacterially_expressed_truncated_protein">a bacterially expressed truncated protein</term> containing the BCL6 zinc fingers can bind <term sem="SPAN" id="T7" lex="specifically">specifically</term> to <term sem="DNA" id="T8" lex="DNA">DNA</term> from the U3 promoter/enhancer region of HIV-1.</sentence>
<event id="E4">
<type class="GRE" />
<Agent idref="T5" idref1="T6" />
<Manner idref="T7" />
<Destination idref="T8" />
<clue>Electrophoretic mobility shift assays showed that the full-length BCL6 protein extracted from transfected COS cells and a bacterially expressed truncated protein containing the BCL6 zinc fingers can <clueType>bind</clueType> specifically to DNA from the U3 promoter/enhancer region of HIV-1.</clue>
</event>
<sentence id="S6">Transient transfections were performed to analyze the effects of <term sem="Repressor" id="T9" lex="the_BCL6_protein">the BCL6 protein</term> on <term sem="Enzyme" id="T10" lex="luciferase">luciferase</term> expression driven by the HIV-1 long terminal repeat (<term sem="DNA" id="T11" lex="LTR">LTR</term>) sequences.</sentence>
<event id="E5">
<type class="GRE" />
<Agent idref="T9" />
<Theme idref="E6" />
<clue>Transient transfections were performed to analyze the <clueType>effects</clueType> of the BCL6 protein on luciferase expression driven by the HIV-1 long terminal repeat (LTR) sequences.</clue>
</event>
<event id="E6">
<type class="Gene_Activation" />
<Theme idref="T10" />
<clue>Transient transfections were performed to analyze the effects of the BCL6 protein on luciferase <clueType>expression</clueType> driven by the HIV-1 long terminal repeat (LTR) sequences.</clue>
</event>
<event id="E7">
<type class="GRE" />
<Agent idref="T11" />
<Theme idref="E6" />
<clue>Transient transfections were performed to analyze the effects of the BCL6 protein on luciferase expression <clueType>driven</clueType> by the HIV-1 long terminal repeat (LTR) sequences.</clue>
</event>
<sentence id="S7"><term sem="Repressor" id="T12" lex="Full-length_BCL6">Full-length BCL6</term> significantly repressed <term sem="SPAN" id="T13" lex="luciferase_activity">luciferase activity</term> compared with multiple controls.</sentence>
<event id="E8">
<type class="GRE" />
<Agent idref="T12" />
<Theme idref="T13" />
<clue>Full-length BCL6 significantly <clueType>repressed</clueType> luciferase activity compared with multiple controls.</clue>
</event>
<sentence id="S8">We conclude that <term sem="Repressor" id="T14" lex="the_BCL6_protein">the BCL6 protein</term> can bind to <term sem="Enhancer" id="T15" lex="the_HIV-1_promoter-enhancer_region">the HIV-1 promoter-enhancer region</term> and contains a domain upstream of <term sem="Domain" id="T16" lex="its_zinc_fingers">its zinc fingers</term> that can repress transcription from <term sem="Enhancer" id="T17" lex="the_HIV-1_LTR">the HIV-1 LTR</term>.</sentence>
<event id="E9">
<type class="GRE" />
<Agent idref="T14" />
<Theme idref="T15" />
<clue>We conclude that the BCL6 protein can <clueType>bind</clueType> to the HIV-1 promoter-enhancer region and contains a domain upstream of its zinc fingers that can repress transcription from the HIV-1 LTR.</clue>
</event>
<event id="E10">
<type class="GRE" />
<Agent idref="T16" />
<Theme idref="E11" />
<clue>We conclude that the BCL6 protein can bind to the HIV-1 promoter-enhancer region and contains a domain upstream of its zinc fingers that can <clueType>repress</clueType> transcription from the HIV-1 LTR.</clue>
</event>
<event id="E11">
<type class="Transcription" />
<Source idref="T17" />
<clue>We conclude that the BCL6 protein can bind to the HIV-1 promoter-enhancer region and contains a domain upstream of its zinc fingers that can repress <clueType>transcription</clueType> from the HIV-1 LTR.</clue>
</event>
</AbstractText>
</Abstract>
</Article>
</MedlineCitation>
</PubmedArticle>
</PubmedArticleSet>
</Annotation>

=== agentile/GREC-MRS/GREC_XML/Human/9787080.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Annotation PUBLIC "-//GREC//DTD GREC EVENT ANNOTATION//EN" "../GRECResources/GREC_event.dtd">
<Annotation created="11/5/2009" creator="mobbedo2" annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;retmode=xml&amp;rettype=medline&amp;id=9787080">
<PubmedArticleSet>
<PubmedArticle>
<MedlineCitation>
<PMID>9787080</PMID>
<Article>
<ArticleTitle>
<sentence id="S1">Characterization of a human homologue of the Saccharomyces cerevisiae transcription factor spt3 (SUPT3H).</sentence>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S3"><term sem="Transcription_Factor" id="T1" lex="Spt3">Spt3</term> is a Saccharomyces cerevisiae transcription factor that is required <term sem="SPAN" id="T2" lex="in_vivo">in vivo</term> for the transcription of a number of <term sem="Gene" id="T3" lex="RNA_polymerase_II-transcribed_genes">RNA polymerase II-transcribed genes</term>.</sentence>
<event id="E1">
<type class="GRE" />
<Theme idref="T1" />
<Condition idref="T2" />
<Purpose idref="E2" />
<clue>Spt3 is a Saccharomyces cerevisiae transcription factor that is <clueType>required</clueType> in vivo for the transcription of a number of RNA polymerase II-transcribed genes.</clue>
</event>
<event id="E2">
<type class="Transcription" />
<Theme idref="T3" />
<clue>Spt3 is a Saccharomyces cerevisiae transcription factor that is required in vivo for the <clueType>transcription</clueType> of a number of RNA polymerase II-transcribed genes.</clue>
</event>
<sentence id="S4">We report the cloning of <term sem="Gene" id="T4" lex="the_gene">the gene</term> encoding the human homologue of Spt3, <term sem="Transcription_Factor" id="T5" lex="SUPT3H">SUPT3H</term>, and its initial functional analysis.</sentence>
<event id="E3">
<type class="GRE" />
<Agent idref="T4" />
<Theme idref="T5" />
<clue>We report the cloning of the gene <clueType>encoding</clueType> the human homologue of Spt3, SUPT3H, and its initial functional analysis.</clue>
</event>
<sentence id="S5">The human and yeast Spt3 homologues share an overall identity of 30% that defines three conserved regions, suggesting possible functional domains.</sentence>
<sentence id="S6">To determine whether SUPT3H is a true functional Spt3 homologue, we tested for complementation of an spt3Delta mutation in yeast.</sentence>
<sentence id="S7">While expression of <term sem="Transcription_Factor" id="T6" lex="the_full-length_SUPT3H">the full-length SUPT3H</term> is <term sem="SPAN" id="T7" lex="unable">unable</term> to complement <term sem="Mutation" id="T8" lex="an_spt3Delta_mutation">an spt3Delta mutation</term>, expression of <term sem="Gene" id="T9" lex="a_human-yeast_chimeric_gene">a human-yeast chimeric gene</term> that contains 42% human sequences can <term sem="SPAN" id="T10" lex="partially">partially</term> complement <term sem="Mutation" id="T11" lex="an_spt3Delta_mutation">an spt3Delta mutation</term>.</sentence>
<event id="E4">
<type class="Gene_Expression" />
<Theme idref="T6" />
<clue>While <clueType>expression</clueType> of the full-length SUPT3H is unable to complement an spt3Delta mutation, expression of a human-yeast chimeric gene that contains 42% human sequences can partially complement an spt3Delta mutation.</clue>
</event>
<event id="E5">
<type class="GRE" />
<Agent idref="T6" />
<Theme idref="T8" />
<Manner idref="T7" />
<clue>While expression of the full-length SUPT3H is unable to <clueType>complement</clueType> an spt3Delta mutation, expression of a human-yeast chimeric gene that contains 42% human sequences can partially complement an spt3Delta mutation.</clue>
</event>
<event id="E6">
<type class="Gene_Expression" />
<Theme idref="T9" />
<clue>While expression of the full-length SUPT3H is unable to complement an spt3Delta mutation, <clueType>expression</clueType> of a human-yeast chimeric gene that contains 42% human sequences can partially complement an spt3Delta mutation.</clue>
</event>
<event id="E7">
<type class="GRE" />
<Agent idref="E6" />
<Theme idref="T11" />
<Manner idref="T10" />
<clue>While expression of the full-length SUPT3H is unable to complement an spt3Delta mutation, expression of a human-yeast chimeric gene that contains 42% human sequences can partially <clueType>complement</clueType> an spt3Delta mutation.</clue>
</event>
<sentence id="S8">These data suggest that <term sem="SPAN" id="T12" lex="the_transcriptional_control">the transcriptional control</term> carried out by Spt3 has been conserved <term sem="SPAN" id="T13" lex="from_yeast_to_human">from <term sem="Wild_Type_Organism" id="T14" lex="yeast">yeast</term> to human</term><term sem="Wild_Type_Organism" id="T15" lex="human"></term>.</sentence>
<event id="E8">
<type class="GRE" />
<Theme idref="T12" />
<Location idref="T13" />
<clue>These data suggest that the transcriptional control carried out by Spt3 has been <clueType>conserved</clueType> from yeast to human.</clue>
</event>
</AbstractText>
</Abstract>
</Article>
</MedlineCitation>
</PubmedArticle>
</PubmedArticleSet>
</Annotation>

=== agentile/GREC-MRS/GREC_XML/Ecoli/9524262.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Annotation PUBLIC "-//GREC//DTD GREC EVENT ANNOTATION//EN" "../GRECResources/GREC_event.dtd">
<Annotation created="11/5/2009" creator="a1" annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;retmode=xml&amp;rettype=medline&amp;id=9524262">
<PubmedArticleSet>
<PubmedArticle>
<MedlineCitation>
<PMID>9524262</PMID>
<Article>
<ArticleTitle>
<sentence id="S1">Cloning and analysis of <term sem="Gene" id="T1" lex="the_shiA_gene">the shiA gene</term>, which encodes <term sem="Protein" id="T2" lex="the_shikimate_transport_system">the shikimate transport system</term> of escherichia coli K-12.</sentence>
<event id="E1">
<type class="Experimental_Technique" />
<Theme idref="T1" />
<clue>Cloning and <clueType>analysis</clueType> of the shiA gene, which encodes the shikimate transport system of escherichia coli K-12.</clue>
</event>
<event id="E2">
<type class="GRE" />
<Agent idref="T1" />
<Theme idref="T2" />
<clue>Cloning and analysis of the shiA gene, which <clueType>encodes</clueType> the shikimate transport system of escherichia coli K-12.</clue>
</event>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S3">In Escherichia coli K-12, <term sem="Gene" id="T3" lex="the_shiA_gene">the shiA gene</term> is involved in <term sem="SPAN" id="T4" lex="the_uptake">the uptake</term> of shikimate.</sentence>
<event id="E3">
<type class="GRE" />
<Agent idref="T3" />
<Descriptive-Agent idref="T4" />
<clue>In Escherichia coli K-12, the shiA gene <clueType>is involved</clueType> in the uptake of shikimate.</clue>
</event>
<sentence id="S4">This gene has been cloned and its nucleotide sequence determined.</sentence>
<sentence id="S5"><term sem="Gene" id="T5" lex="The_gene">The gene</term> is predicted to encode <term sem="Protein" id="T6" lex="a_protein">a protein</term> of 438 amino acids and lies adjacent to the amn gene.</sentence>
<event id="E4">
<type class="GRE" />
<Agent idref="T5" />
<Theme idref="T6" />
<clue>The gene is predicted to <clueType>encode</clueType> a protein of 438 amino acids and lies adjacent to the amn gene.</clue>
</event>
<sentence id="S6">The hydropathy profile and the amino acid sequence indicate that the ShiA protein is a polytopic membrane protein that shows a homology with members of the major facilitator superfamily of transport proteins.</sentence>
<sentence id="S7">Recombining <term sem="Gene" id="T7" lex="an_inactive_form">an inactive form</term> of the cloned gene into <term sem="Chromosome" id="T8" lex="the_chromosome">the chromosome</term> creates <term sem="Mutant_Gene" id="T9" lex="mutants">mutants</term> unable to transport shikimate.</sentence>
<event id="E5">
<type class="Recombination" />
<Theme idref="T7" />
<Destination idref="T8" />
<clue><clueType>Recombining</clueType> an inactive form of the cloned gene into the chromosome creates mutants unable to transport shikimate.</clue>
</event>
<event id="E6">
<type class="GRE" />
<Agent idref="E5" />
<Theme idref="T9" />
<clue>Recombining an inactive form of the cloned gene into the chromosome <clueType>creates</clueType> mutants unable to transport shikimate.</clue>
</event>
<sentence id="S8">Introducing a wild-type gene on a multicopy plasmid into a shiA mutant restores the ability to transport shikimate.</sentence>
<sentence id="S9">When this multicopy shiA plasmid is introduced into an aroE strain, this strain is now able to grow with shikimate as the aromatic supplement, consistent with the notion that dehydroshikimate (DHS) accumulated in an aroE strain prevents uptake of shikimate by competition.</sentence>
<sentence id="S10">Expression of <term sem="Gene" id="T10" lex="the_shiA_gene">the shiA gene</term> does not appear to be regulated by <term sem="Regulator" id="T11" lex="the_TyrR_protein">the TyrR protein</term>, a repressor/activator that controls the expression of <term sem="Gene" id="T12" lex="other_genes">other genes</term> involved with <term sem="SPAN" id="T13" lex="the_biosynthesis_or_transport">the biosynthesis or transport</term> of the aromatic amino acids.</sentence>
<event id="E7">
<type class="Gene_Expression" />
<Theme idref="T10" />
<clue><clueType>Expression</clueType> of the shiA gene does not appear to be regulated by the TyrR protein, a repressor/activator that controls the expression of other genes involved with the biosynthesis or transport of the aromatic amino acids.</clue>
</event>
<event id="E8">
<type class="GRE" />
<Agent idref="T11" />
<Theme idref="E7" />
<clue>Expression of the shiA gene does not appear to be <clueType>regulated</clueType> by the TyrR protein, a repressor/activator that controls the expression of other genes involved with the biosynthesis or transport of the aromatic amino acids.</clue>
</event>
<event id="E9">
<type class="GRE" />
<Agent idref="T11" />
<Theme idref="E10" />
<clue>Expression of the shiA gene does not appear to be regulated by the TyrR protein, a repressor/activator that <clueType>controls</clueType> the expression of other genes involved with the biosynthesis or transport of the aromatic amino acids.</clue>
</event>
<event id="E10">
<type class="Gene_Expression" />
<Theme idref="T12" />
<clue>Expression of the shiA gene does not appear to be regulated by the TyrR protein, a repressor/activator that controls the <clueType>expression</clueType> of other genes involved with the biosynthesis or transport of the aromatic amino acids.</clue>
</event>
<event id="E11">
<type class="GRE" />
<Agent idref="T12" />
<Descriptive-Agent idref="T13" />
<clue>Expression of the shiA gene does not appear to be regulated by the TyrR protein, a repressor/activator that controls the expression of other genes <clueType>involved</clueType> with the biosynthesis or transport of the aromatic amino acids.</clue>
</event>
</AbstractText>
</Abstract>
</Article>
</MedlineCitation>
</PubmedArticle>
</PubmedArticleSet>
</Annotation>

=== agentile/GREC-MRS/GREC_XML/Human/9647758.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Annotation PUBLIC "-//GREC//DTD GREC EVENT ANNOTATION//EN" "../GRECResources/GREC_event.dtd">
<Annotation created="11/5/2009" creator="a3" annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;retmode=xml&amp;rettype=medline&amp;id=9647758">
<PubmedArticleSet>
<PubmedArticle>
<MedlineCitation>
<PMID>9647758</PMID>
<Article>
<ArticleTitle>
<sentence id="S1">Identification of a novel isoform of microphthalmia-associated transcription factor that is enriched in retinal pigment epithelium.</sentence>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S3"><term sem="Mutation" id="T1" lex="Mutations">Mutations</term> at <term sem="Locus" id="T2" lex="the_mouse_locus">the mouse locus</term> encoding microphthalmia-associated transcription factor (<term sem="Transcription_Factor" id="T3" lex="Mitf">Mitf</term>) affect <term sem="SPAN" id="T4" lex="the_development_of_many_cell_types">the development of <term sem="Cells" id="T5" lex="many_cell_types">many cell types</term></term>, including retinal pigment epithelium (RPE), melanocytes, mast cells, and osteoclasts.</sentence>
<event id="E1">
<type class="GRE" />
<Agent idref="T2" />
<Theme idref="T3" />
<clue>Mutations at the mouse locus <clueType>encoding</clueType> microphthalmia-associated transcription factor (Mitf) affect the development of many cell types, including retinal pigment epithelium (RPE), melanocytes, mast cells, and osteoclasts.</clue>
</event>
<event id="E2">
<type class="GRE" />
<Agent idref="T1" />
<Theme idref="T4" />
<clue>Mutations at the mouse locus encoding microphthalmia-associated transcription factor (Mitf) <clueType>affect</clueType> the development of many cell types, including retinal pigment epithelium (RPE), melanocytes, mast cells, and osteoclasts.</clue>
</event>
<sentence id="S4">Here we have identified a novel Mitf isoform, Mitf-a, and its human homologue MITF-A by cDNA cloning.</sentence>
<sentence id="S5">MITF-A consists of 520 amino acid residues and differs in the amino-terminus from authentic melanocyte-type MITF (MITF-M).</sentence>
<sentence id="S6"><term sem="mRNA" id="T6" lex="MITF-A_mRNA">MITF-A mRNA</term> is <term sem="SPAN" id="T7" lex="widely">widely</term> expressed and represents a <term sem="Transcription_Factor" id="T8" lex="predominant_MITF_isoform">predominant MITF isoform</term> <term sem="SPAN" id="T9" lex="in_cultured_RPE_cells">in cultured RPE cells</term>, whereas <term sem="mRNA" id="T10" lex="MITF-M_mRNA">MITF-M mRNA</term> is <term sem="SPAN" id="T11" lex="exclusively">exclusively</term> expressed <term sem="SPAN" id="T12" lex="in_melanocytes_and_melanoma_cells">in <term sem="Cells" id="T13" lex="melanocytes">melanocytes</term> and melanoma cells</term>.</sentence>
<event id="E3">
<type class="Gene_Expression" />
<Theme idref="T6" />
<Manner idref="T7" />
<clue>MITF-A mRNA is widely <clueType>expressed</clueType> and represents a predominant MITF isoform in cultured RPE cells, whereas MITF-M mRNA is exclusively expressed in melanocytes and melanoma cells.</clue>
</event>
<event id="E4">
<type class="GRE" />
<Theme idref="T6" />
<Location idref="T9" />
<Descriptive-Theme idref="T8" />
<clue>MITF-A mRNA is widely expressed and <clueType>represents</clueType> a predominant MITF isoform in cultured RPE cells, whereas MITF-M mRNA is exclusively expressed in melanocytes and melanoma cells.</clue>
</event>
<event id="E5">
<type class="Gene_Expression" />
<Theme idref="T10" />
<Manner idref="T11" />
<Location idref="T12" />
<clue>MITF-A mRNA is widely expressed and represents a predominant MITF isoform in cultured RPE cells, whereas MITF-M mRNA is exclusively <clueType>expressed</clueType> in melanocytes and melanoma cells.</clue>
</event>
<sentence id="S7">In situ hybridization analysis suggested that Mitf-a mRNA is enriched in the prospective RPE of mouse embryo.</sentence>
<sentence id="S8">Moreover, transient cotransfection assays suggested that <term sem="Transcription_Factor" id="T14" lex="MITF-A">MITF-A</term> activated transcription of <term sem="Gene" id="T15" lex="the_tyrosinase"><term sem="SPAN" id="T16" lex="the_tyrosinase_and_tyrosinase-related_protein_1_genes">the tyrosinase and tyrosinase-related protein 1 genes</term></term>.</sentence>
<event id="E6">
<type class="Gene_Activation" />
<Agent idref="T14" />
<Theme idref="E7" />
<clue>Moreover, transient cotransfection assays suggested that MITF-A <clueType>activated</clueType> transcription of the tyrosinase and tyrosinase-related protein 1 genes.</clue>
</event>
<event id="E7">
<type class="Transcription" />
<Theme idref="T16" />
<clue>Moreover, transient cotransfection assays suggested that MITF-A activated <clueType>transcription</clueType> of the tyrosinase and tyrosinase-related protein 1 genes.</clue>
</event>
<sentence id="S9">MITF-A/Mitf-a therefore may play an important role in melanogenesis in RPE.</sentence>
</AbstractText>
</Abstract>
</Article>
</MedlineCitation>
</PubmedArticle>
</PubmedArticleSet>
</Annotation>
