=== agentile/GREC-MRS/GREC_XML/GRECResources/GREC_event.dtd
<!-- ============================================================ -->
<!-- DTD for GREC with concept &    event annotation              -->
<!-- Modified by Paul Thompson <paul.thompson@manchester.ac.uk>   -->
<!-- from the original GENIA DTD written by Jin-Dong KIM          -->
<!-- <jdkim@tsujii.is.s.u-tokyo.ac.jp>  				      -->
<!-- Date of last modification: 28 August 2009                    -->
<!-- ============================================================ -->

<!-- ============================================================ -->
<!-- Labels for concept&event annotation                             -->
<!-- ============================================================ -->
<!ENTITY % term.class "(
 Polypeptide | Peptide | Protein_Complex | Protein | Amino_Acids |
 Conformation | Sub_Unit | Motif | Domain | Transcription_Factor |
 Enzyme | Regulator | Sigma_Factor | Repressor | Rho-Factor |
 Activator | RNA_Polymerase | DNA_Polymerase | Restriction_Enzyme |
 Chromosome | Plasmid | Viral_Vector | RNA | DNA | Gene | Operon |
 Locus | Mutant_Gene | ORF | Allele | Transcription_Binding_Site |
 Termination_Site | Phenotype | Ribosome | mRNA | Promoter | Operator |
 Enhancer | Prokaryotes | Virus | Eukaryotes | Bacteria | Non-Bacteria |
 Wild_Type_Bacteria | Mutant_Bacteria | Organism | Tissue | Cells |Organelles |
 Wild_Type_Organism | Mutant_Organism | Gene_Expression |
 Mutation | Transcription | Replication | Recombination | Methylation | Regulation |
 Gene_Activation | Gene_Repression | Insertion | Deletion | Null_Mutation | Point_Mutation |
 Reagents | Experimental_Technique | Experimental_Equipment | Inorganic_Compounds | 
 Organic_Compounds | Other_Compounds | Laboratory_Technique | Computational_Analysis | SPAN 
)">

<!-- ============================================================ -->
<!-- HIERARCHICAL ELEMENTS                                        -->
<!-- ============================================================ -->
<!ELEMENT Annotation (PubmedArticleSet)>
<!ATTLIST Annotation
		annotates CDATA #REQUIRED
		creator   CDATA #IMPLIED
		created   CDATA #IMPLIED
>

<!ELEMENT PubmedArticleSet (PubmedArticle)>
<!ELEMENT PubmedArticle (MedlineCitation)>
<!ELEMENT MedlineCitation (PMID, Article)>
<!ELEMENT Article (ArticleTitle, Abstract)>
<!ELEMENT Abstract (AbstractText)>

<!-- ============================================================ -->
<!-- BLOCK ELEMENTS                                               -->
<!-- ============================================================ -->
<!ELEMENT ArticleTitle (sentence | event)+>
<!ELEMENT AbstractText (sentence | event)+>
<!ELEMENT PMID (#PCDATA)>

<!-- ============================================================ -->
<!-- LINGUISTIC ELEMENTS                                          -->
<!-- ============================================================ -->
<!ELEMENT sentence	(#PCDATA | term )*>
<!ATTLIST sentence	id ID	#REQUIRED>


<!ELEMENT term		(#PCDATA | term )*>
<!ATTLIST term
		sem %term.class;	#IMPLIED
		lex CDATA		#IMPLIED
		id  ID		#REQUIRED
>

<!-- ============================================================ -->
<!-- ELEMENTS FOR EVENT ANNOTATION                                -->
<!-- ============================================================ -->
<!ELEMENT event (type, (Agent | Theme | Manner | Instrument | Location | Source | Destination | 
Temporal | Condition | Rate | Descriptive-Agent | Descriptive-Theme | Purpose )+,
            clue)>
<!ATTLIST event
		id		ID				#REQUIRED
>

<!ELEMENT type EMPTY>
<!ATTLIST type class		CDATA	"UNCLASSIFIED">

<!ELEMENT Agent EMPTY>
<!ATTLIST Agent
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT Theme EMPTY>
<!ATTLIST Theme
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT Manner EMPTY>
<!ATTLIST Manner
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED

>

<!ELEMENT Instrument EMPTY>
<!ATTLIST Instrument
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED

>

<!ELEMENT Location EMPTY>
<!ATTLIST Location
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED

>

<!ELEMENT Source EMPTY>
<!ATTLIST Source
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED

>

<!ELEMENT Destination EMPTY>
<!ATTLIST Destination
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED

>

<!ELEMENT Temporal EMPTY>
<!ATTLIST Temporal
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED

>

<!ELEMENT Condition EMPTY>
<!ATTLIST Condition
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED

>

<!ELEMENT Rate EMPTY>
<!ATTLIST Rate
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED

>
<!ELEMENT Descriptive-Agent EMPTY>
<!ATTLIST Descriptive-Agent
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>

<!ELEMENT Descriptive-Theme EMPTY>
<!ATTLIST Descriptive-Theme
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED

>
<!ELEMENT Purpose EMPTY>
<!ATTLIST Purpose
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>
<!ELEMENT Underspecified EMPTY>
<!ATTLIST Underspecified
		idref		IDREF	#REQUIRED
		idref1		IDREF	#IMPLIED
		idref2		IDREF	#IMPLIED
		idref3		IDREF	#IMPLIED
		idref4		IDREF	#IMPLIED
		idref5		IDREF	#IMPLIED
>



<!ELEMENT clue  (#PCDATA | clueType)*>

<!ELEMENT clueType		(#PCDATA)>

=== agentile/GREC-MRS/GREC_XML/Ecoli/8577250.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Annotation PUBLIC "-//GREC//DTD GREC EVENT ANNOTATION//EN" "../GRECResources/GREC_event.dtd">
<Annotation created="11/5/2009" creator="a2" annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;retmode=xml&amp;rettype=medline&amp;id=8577250">
<PubmedArticleSet>
<PubmedArticle>
<MedlineCitation>
<PMID>8577250</PMID>
<Article>
<ArticleTitle>
<sentence id="S1"><term sem="Regulator" id="T1" lex="The_global_regulatory_protein_FruR">The global regulatory protein FruR</term> modulates <term sem="SPAN" id="T2" lex="the_direction_of_carbon_flow">the direction of carbon flow</term> <term sem="SPAN" id="T3" lex="in_Escherichia_coli">in <term sem="Wild_Type_Bacteria" id="T4" lex="Escherichia_coli">Escherichia coli</term></term>.</sentence>
<event id="E1">
<type class="GRE" />
<Agent idref="T1" />
<Theme idref="T2" />
<Location idref="T3" />
<clue>The global regulatory protein FruR <clueType>modulates</clueType> the direction of carbon flow in Escherichia coli.</clue>
</event>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S3">The Escherichia coli fructose repressor, <term sem="Regulator" id="T5" lex="FruR">FruR</term>, is known to regulate expression of <term sem="Gene" id="T6" lex="several_genes">several genes</term> concerned with carbon utilization.</sentence>
<event id="E2">
<type class="GRE" />
<Agent idref="T5" />
<Theme idref="E3" />
<clue>The Escherichia coli fructose repressor, FruR, is known to <clueType>regulate</clueType> expression of several genes concerned with carbon utilization.</clue>
</event>
<event id="E3">
<type class="Gene_Expression" />
<Theme idref="T6" />
<clue>The Escherichia coli fructose repressor, FruR, is known to regulate <clueType>expression</clueType> of several genes concerned with carbon utilization.</clue>
</event>
<sentence id="S4">Using <term sem="Operator" id="T7" lex="a_previously_derived_consensus_sequence">a previously derived consensus sequence</term> for <term sem="Regulator" id="T8" lex="FruR">FruR</term> binding, additional potential operators were identified and tested for <term sem="Regulator" id="T9" lex="FruR">FruR</term> binding in DNA band migration retardation assays.</sentence>
<event id="E4">
<type class="GRE" />
<Agent idref="T8" />
<Destination idref="T7" />
<clue>Using a previously derived consensus sequence for FruR <clueType>binding</clueType>, additional potential operators were identified and tested for FruR binding in DNA band migration retardation assays.</clue>
</event>
<event id="E5">
<type class="GRE" />
<Agent idref="T9" />
<clue>Using a previously derived consensus sequence for FruR binding, additional potential operators were identified and tested for FruR <clueType>binding</clueType> in DNA band migration retardation assays.</clue>
</event>
<sentence id="S5"><term sem="Operator" id="T10" lex="Operators">Operators</term> in the control regions of operons concerned with carbon metabolism bound <term sem="Regulator" id="T11" lex="FruR">FruR</term>, while those in operons not concerned with carbon metabolism did not.</sentence>
<event id="E6">
<type class="GRE" />
<Agent idref="T10" />
<Destination idref="T11" />
<clue>Operators in the control regions of operons concerned with carbon metabolism <clueType>bound</clueType> FruR, while those in operons not concerned with carbon metabolism did not.</clue>
</event>
<sentence id="S6">In vivo assays with transcriptional lacZ fusions showed that <term sem="Regulator" id="T12" lex="FruR">FruR</term> controls the expression of <term sem="Gene" id="T13" lex="FruR_operator-containing_genes">FruR operator-containing genes</term> encoding <term sem="Enzyme" id="T14" lex="key_enzymes">key enzymes</term> of virtually every major pathway of carbon metabolism.</sentence>
<event id="E7">
<type class="GRE" />
<Agent idref="T12" />
<Theme idref="E8" />
<clue>In vivo assays with transcriptional lacZ fusions showed that FruR <clueType>controls</clueType> the expression of FruR operator-containing genes encoding key enzymes of virtually every major pathway of carbon metabolism.</clue>
</event>
<event id="E8">
<type class="Gene_Activation" />
<Theme idref="T13" />
<clue>In vivo assays with transcriptional lacZ fusions showed that FruR controls the <clueType>expression</clueType> of FruR operator-containing genes encoding key enzymes of virtually every major pathway of carbon metabolism.</clue>
</event>
<event id="E9">
<type class="GRE" />
<Agent idref="T13" />
<Theme idref="T14" />
<clue>In vivo assays with transcriptional lacZ fusions showed that FruR controls the expression of FruR operator-containing genes <clueType>encoding</clueType> key enzymes of virtually every major pathway of carbon metabolism.</clue>
</event>
<sentence id="S7">Moreover, a <term sem="SPAN" id="T15" lex="fruR_null">fruR null</term> mutation altered <term sem="SPAN" id="T16" lex="the_rates_of_utilization">the rates of utilization</term> of at least 36 carbon sources.</sentence>
<event id="E10">
<type class=" Null_Mutation" />
<Manner idref="T15" />
<clue>Moreover, a fruR null <clueType>mutation</clueType> altered the rates of utilization of at least 36 carbon sources.</clue>
</event>
<event id="E11">
<type class="GRE" />
<Agent idref="E10" />
<Theme idref="T16" />
<clue>Moreover, a fruR null mutation <clueType>altered</clueType> the rates of utilization of at least 36 carbon sources.</clue>
</event>
<sentence id="S8">In general, oxidation rates for glycolytic substances were enhanced while those for gluconeogenic substances were depressed.</sentence>
<sentence id="S9">Alignment of FruR operators revealed that <term sem="Operator" id="T17" lex="the_consensus_sequence">the consensus sequence</term> for <term sem="Regulator" id="T18" lex="FruR">FruR</term> binding is the same for <term sem="Operon" id="T19" lex="operons">operons</term> that are activated and repressed by <term sem="Regulator" id="T20" lex="FruR">FruR</term> and permitted formulation of <term sem="Operator" id="T21" lex="a_revised_FruR-binding_consensus_sequence">a revised FruR-binding consensus sequence</term>.</sentence>
<event id="E12">
<type class="GRE" />
<Agent idref="T18" />
<Destination idref="T17" />
<clue>Alignment of FruR operators revealed that the consensus sequence for FruR <clueType>binding</clueType> is the same for operons that are activated and repressed by FruR and permitted formulation of a revised FruR-binding consensus sequence.</clue>
</event>
<event id="E13">
<type class="GRE" />
<Agent idref="T20" />
<Theme idref="T19" />
<clue>Alignment of FruR operators revealed that the consensus sequence for FruR binding is the same for operons that are <clueType>activated</clueType> and repressed by FruR and permitted formulation of a revised FruR-binding consensus sequence.</clue>
</event>
<event id="E14">
<type class="GRE" />
<Agent idref="T20" />
<Theme idref="T19" />
<clue>Alignment of FruR operators revealed that the consensus sequence for FruR binding is the same for operons that are activated and <clueType>repressed</clueType> by FruR and permitted formulation of a revised FruR-binding consensus sequence.</clue>
</event>
<event id="E15">
<type class="GRE" />
<Agent idref="T17" />
<Theme idref="E16" />
<clue>Alignment of FruR operators revealed that the consensus sequence for FruR binding is the same for operons that are activated and repressed by FruR and <clueType>permitted</clueType> formulation of a revised FruR-binding consensus sequence.</clue>
</event>
<event id="E16">
<type class="GRE" />
<Theme idref="T21" />
<clue>Alignment of FruR operators revealed that the consensus sequence for FruR binding is the same for operons that are activated and repressed by FruR and permitted <clueType>formulation</clueType> of a revised FruR-binding consensus sequence.</clue>
</event>
<sentence id="S10">The reported observations indicate that <term sem="Regulator" id="T22" lex="FruR">FruR</term> modulates the direction of carbon flow by <term sem="SPAN" id="T23" lex="transcriptional">transcriptional</term> activation of <term sem="Gene" id="T24" lex="genes">genes</term> encoding <term sem="Enzyme" id="T25" lex="enzymes">enzymes</term> concerned with oxidative and gluconeogenic carbon flow and by <term sem="Gene_Repression" id="T26" lex="repression">repression</term> of those concerned with fermentative carbon flow.</sentence>
<event id="E17">
<type class="Gene_Repression" />
<Theme idref="T24" />
<Manner idref="T23" />
<clue>The reported observations indicate that FruR modulates the direction of carbon flow by transcriptional <clueType>activation</clueType> of genes encoding enzymes concerned with oxidative and gluconeogenic carbon flow and by repression of those concerned with fermentative carbon flow.</clue>
</event>
<event id="E18">
<type class="GRE" />
<Agent idref="T24" />
<Theme idref="T25" />
<clue>The reported observations indicate that FruR modulates the direction of carbon flow by transcriptional activation of genes <clueType>encoding</clueType> enzymes concerned with oxidative and gluconeogenic carbon flow and by repression of those concerned with fermentative carbon flow.</clue>
</event>
</AbstractText>
</Abstract>
</Article>
</MedlineCitation>
</PubmedArticle>
</PubmedArticleSet>
</Annotation>

=== agentile/GREC-MRS/GREC_XML/Ecoli/1310090.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Annotation PUBLIC "-//GREC//DTD GREC EVENT ANNOTATION//EN" "../GRECResources/GREC_event.dtd">
<Annotation created="11/5/2009" creator="a6" annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;retmode=xml&amp;rettype=medline&amp;id=1310090">
<PubmedArticleSet>
<PubmedArticle>
<MedlineCitation>
<PMID>1310090</PMID>
<Article>
<ArticleTitle>
<sentence id="S1">Positive and negative control of <term sem="SPAN" id="T1" lex="ompB">ompB</term> transcription <term sem="SPAN" id="T2" lex="in_Escherichia_coli">in <term sem="Wild_Type_Bacteria" id="T3" lex="Escherichia_coli">Escherichia coli</term></term> by <term sem="Organic_Compounds" id="T4" lex="cyclic_AMP">cyclic AMP</term> and <term sem="Protein" id="T5" lex="the_cyclic_AMP_receptor_protein">the cyclic AMP receptor protein</term>.</sentence>
<event id="E1">
<type class="Transcription" />
<Agent idref="T4" idref1="T5" />
<Theme idref="T1" />
<Location idref="T2" />
<clue>Positive and negative control of ompB <clueType>transcription</clueType> in Escherichia coli by cyclic AMP and the cyclic AMP receptor protein.</clue>
</event>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S3"><term sem="Operon" id="T6" lex="The_ompB_operon">The ompB operon</term> encodes <term sem="Protein" id="T7" lex="OmpR_and_EnvZ">OmpR and EnvZ</term>, two proteins that are necessary for the expression and osmoregulation of <term sem="Protein" id="T8" lex="the_OmpF_and_OmpC_porins">the OmpF and OmpC porins</term> <term sem="SPAN" id="T9" lex="in_Escherichia_coli">in <term sem="Wild_Type_Bacteria" id="T10" lex="Escherichia_coli">Escherichia coli</term></term>.</sentence>
<event id="E2">
<type class="GRE" />
<Agent idref="T6" />
<Theme idref="T7" />
<clue>The ompB operon <clueType>encodes</clueType> OmpR and EnvZ, two proteins that are necessary for the expression and osmoregulation of the OmpF and OmpC porins in Escherichia coli.</clue>
</event>
<event id="E3">
<type class="Gene_Expression" />
<Theme idref="T8" />
<Location idref="T9" />
<clue>The ompB operon encodes OmpR and EnvZ, two proteins that are necessary for the <clueType>expression</clueType> and osmoregulation of the OmpF and OmpC porins in Escherichia coli.</clue>
</event>
<event id="E4">
<type class="Regulation" />
<Theme idref="T8" />
<Location idref="T9" />
<clue>The ompB operon encodes OmpR and EnvZ, two proteins that are necessary for the expression and <clueType>osmoregulation</clueType> of the OmpF and OmpC porins in Escherichia coli.</clue>
</event>
<sentence id="S4">We have used in vitro and in vivo experiments to show that cyclic AMP and the cyclic AMP receptor protein (CRP) directly regulate ompB.</sentence>
<sentence id="S5"><term sem="Gene" id="T11" lex="ompB">ompB</term> expression <term sem="SPAN" id="T12" lex="in_an_ompB-lacZ_chromosomal_fusion_strain">in <term sem=" Mutant_Bacteria" id="T13" lex="an_ompB-lacZ_chromosomal_fusion_strain">an ompB-lacZ chromosomal fusion strain</term></term> was increased <term sem="SPAN" id="T14" lex="two-_to_fivefold">two- to fivefold</term> <term sem="SPAN" id="T15" lex="when_cells_were_grown">when <term sem="Wild_Type_Bacteria" id="T16" lex="cells">cells</term> were grown</term> in <term sem="Organic_Compounds" id="T17" lex="medium_containing_poor_carbon_sources_or_with_added_cyclic_AMP">medium containing poor carbon sources or with added cyclic AMP</term>.</sentence>
<event id="E5">
<type class="Gene_Expression" />
<Theme idref="T11" />
<Location idref="T12" />
<clue>ompB <clueType>expression</clueType> in an ompB-lacZ chromosomal fusion strain was increased two- to fivefold when cells were grown in medium containing poor carbon sources or with added cyclic AMP.</clue>
</event>
<event id="E6">
<type class="GRE" />
<Theme idref="E5" />
<Condition idref="T17" />
<Rate idref="T14" />
<Temporal idref="T15" />
<clue>ompB expression in an ompB-lacZ chromosomal fusion strain was <clueType>increased</clueType> two- to fivefold when cells were grown in medium containing poor carbon sources or with added cyclic AMP.</clue>
</event>
<sentence id="S6">In vivo primer extension analysis indicated that <term sem="SPAN" id="T18" lex="this_control">this control</term> is complex and involves both <term sem="SPAN" id="T19" lex="positive_and_negative">positive and negative</term> effects by <term sem="Protein_Complex" id="T20" lex="cyclic_AMP-CRP">cyclic AMP-CRP</term> <term sem="SPAN" id="T21" lex="on_multiple_ompB_promoters">on <term sem="Promoter" id="T22" lex="multiple_ompB_promoters">multiple ompB promoters</term></term>.</sentence>
<event id="E7">
<type class="GRE" />
<Theme idref="T18" />
<Descriptive-Theme idref="E8" />
<clue>In vivo primer extension analysis indicated that this control is complex and <clueType>involves</clueType> both positive and negative effects by cyclic AMP-CRP on multiple ompB promoters.</clue>
</event>
<event id="E8">
<type class="GRE" />
<Agent idref="T20" />
<Manner idref="T19" />
<Location idref="T21" />
<clue>In vivo primer extension analysis indicated that this control is complex and involves both positive and negative <clueType>effects</clueType> by cyclic AMP-CRP on multiple ompB promoters.</clue>
</event>
<sentence id="S7">In vitro footprinting showed that <term sem="Protein_Complex" id="T23" lex="cyclic_AMP-CRP">cyclic AMP-CRP</term> binds to <term sem="Locus" id="T24" lex="a_34-bp_site">a 34-bp site</term> centered at -53 and at -75 in relation to the start sites of <term sem="mRNA" id="T25" lex="the_major_transcripts">the major transcripts</term> that are inhibited and activated, respectively, by <term sem="Protein_Complex" id="T26" lex="this_complex">this complex</term>.</sentence>
<event id="E9">
<type class="GRE" />
<Agent idref="T23" />
<Destination idref="T24" />
<clue>In vitro footprinting showed that cyclic AMP-CRP <clueType>binds</clueType> to a 34-bp site centered at -53 and at -75 in relation to the start sites of the major transcripts that are inhibited and activated, respectively, by this complex.</clue>
</event>
<event id="E10">
<type class="Gene_Repression" />
<Agent idref="T26" />
<Theme idref="T25" />
<clue>In vitro footprinting showed that cyclic AMP-CRP binds to a 34-bp site centered at -53 and at -75 in relation to the start sites of the major transcripts that are <clueType>inhibited</clueType> and activated, respectively, by this complex.</clue>
</event>
<event id="E11">
<type class="Gene_Activation" />
<Agent idref="T26" />
<Theme idref="T25" />
<clue>In vitro footprinting showed that cyclic AMP-CRP binds to a 34-bp site centered at -53 and at -75 in relation to the start sites of the major transcripts that are inhibited and <clueType>activated</clueType>, respectively, by this complex.</clue>
</event>
<sentence id="S8">Site-directed mutagenesis of the crp binding site provided evidence that this site is necessary for the <term sem="SPAN" id="T27" lex="in_vivo">in vivo</term> regulation of <term sem="Gene" id="T28" lex="ompB">ompB</term> expression by <term sem="Organic_Compounds" id="T29" lex="cyclic_AMP">cyclic AMP</term>.</sentence>
<event id="E12">
<type class="Regulation" />
<Agent idref="T29" />
<Theme idref="E13" />
<Manner idref="T27" />
<clue>Site-directed mutagenesis of the crp binding site provided evidence that this site is necessary for the in vivo <clueType>regulation</clueType> of ompB expression by cyclic AMP.</clue>
</event>
<event id="E13">
<type class="Gene_Expression" />
<Theme idref="T28" />
<clue>Site-directed mutagenesis of the crp binding site provided evidence that this site is necessary for the in vivo regulation of ompB <clueType>expression</clueType> by cyclic AMP.</clue>
</event>
<sentence id="S9">Control of <term sem="Operon" id="T30" lex="the_ompB_operon">the ompB operon</term> by <term sem="Protein_Complex" id="T31" lex="cyclic_AMP-CRP">cyclic AMP-CRP</term> may account for the observed regulation of the formation of <term sem="Protein" id="T32" lex="OmpF_and_OmpC">OmpF and OmpC</term> by <term sem="Protein_Complex" id="T33" lex="this_complex">this complex</term> (N.W. Scott and C.R. Harwood, FEMS Microbiol. Lett. 9:95-98, 1980).</sentence>
<event id="E14">
<type class="GRE" />
<Agent idref="T31" />
<Theme idref="T30" />
<clue><clueType>Control</clueType> of the ompB operon by cyclic AMP-CRP may account for the observed regulation of the formation of OmpF and OmpC by this complex (N.W. Scott and C.R. Harwood, FEMS Microbiol. Lett. 9:95-98, 1980).</clue>
</event>
<event id="E15">
<type class="Regulation" />
<Theme idref="E16" />
<clue>Control of the ompB operon by cyclic AMP-CRP may account for the observed <clueType>regulation</clueType> of the formation of OmpF and OmpC by this complex (N.W. Scott and C.R. Harwood, FEMS Microbiol. Lett. 9:95-98, 1980).</clue>
</event>
<event id="E16">
<type class="GRE" />
<Agent idref="T33" />
<Theme idref="T32" />
<clue>Control of the ompB operon by cyclic AMP-CRP may account for the observed regulation of the <clueType>formation</clueType> of OmpF and OmpC by this complex (N.W. Scott and C.R. Harwood, FEMS Microbiol. Lett. 9:95-98, 1980).</clue>
</event>
</AbstractText>
</Abstract>
</Article>
</MedlineCitation>
</PubmedArticle>
</PubmedArticleSet>
</Annotation>

=== agentile/GREC-MRS/GREC_XML/Human/7607690.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Annotation PUBLIC "-//GREC//DTD GREC EVENT ANNOTATION//EN" "../GRECResources/GREC_event.dtd">
<Annotation created="11/5/2009" creator="a6" annotates="http://www.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pubmed&amp;retmode=xml&amp;rettype=medline&amp;id=7607690">
<PubmedArticleSet>
<PubmedArticle>
<MedlineCitation>
<PMID>7607690</PMID>
<Article>
<ArticleTitle>
<sentence id="S1">Identification of a new murine runt domain-containing gene, Cbfa3, and localization of the human homolog, CBFA3, to chromosome 1p35-pter.</sentence>
</ArticleTitle>
<Abstract>
<AbstractText>
<sentence id="S3">Core binding factor (CBF) is a heterodimeric transcription factor composed of two distinct subunits.</sentence>
<sentence id="S4"><term sem="Sub_Unit" id="T1" lex="The_monomeric_beta_subunit">The monomeric beta subunit</term> is <term sem="SPAN" id="T2" lex="ubiquitously">ubiquitously</term> expressed, whereas expression of <term sem="Sub_Unit" id="T3" lex="the_three_alpha_subunits">the three alpha subunits</term> isolated previously seems to be restricted mainly to hematopoietic tissues.</sentence>
<event id="E1">
<type class="Gene_Expression" />
<Theme idref="T1" />
<Manner idref="T2" />
<clue>The monomeric beta subunit is ubiquitously <clueType>expressed</clueType>, whereas expression of the three alpha subunits isolated previously seems to be restricted mainly to hematopoietic tissues.</clue>
</event>
<event id="E2">
<type class="Gene_Expression" />
<Theme idref="T3" />
<clue>The monomeric beta subunit is ubiquitously expressed, whereas <clueType>expression</clueType> of the three alpha subunits isolated previously seems to be restricted mainly to hematopoietic tissues.</clue>
</event>
<sentence id="S5">To isolate additional alpha genes, degenerate oligonucleotides derived from the runt domain--a region shared by all alpha genes--were used for screening cDNA libraries.</sentence>
<sentence id="S6">A 228-bp fragment was isolated from a mouse thymus cDNA library, which showed 82 and 76% DNA sequence identity to the previously isolated murine alpha genes, Cbfa1 and Cbfa2.</sentence>
<sentence id="S7">This novel alpha gene was named Cbfa3.</sentence>
<sentence id="S8">The corresponding sequence from the human homolog CBFA3 was obtained by cosmid cloning and sequencing of the appropriate restriction fragment.</sentence>
<sentence id="S9">The corresponding regions of mouse Cbfa3 and human CBFA3 show 91% nucleotide identity and 100% protein identity.</sentence>
<sentence id="S10">In situ hybridization and physical mapping of somatic cell hybrids localized CBFA3 to chromosome 1p35-pter.</sentence>
</AbstractText>
</Abstract>
</Article>
</MedlineCitation>
</PubmedArticle>
</PubmedArticleSet>
</Annotation>
